-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHvY8JFtK/ca3FBeb
B8FBEYiMGEYBvDV3oWfdN4uco6WgCgYIKoZIzj0DAQehRANCAAT6EBnADsIIcNk1
mBAZNKNpjT/vw38HqTO/nxsQwwhWvJA5BhbPs8tW0CaKCJEpZX/gLgCJaXC8MRSJ
6qLBKXPV
-----END PRIVATE KEY-----