name: sultan_cab
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.5"

dependencies:
  assets_audio_player: ^3.0.5
  cached_network_image: ^3.2.1
  country_code_picker: ^2.0.2
  dropdown_below: ^1.0.3
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  #    View

  flutter_local_notifications: ^13.0.0
  flutter_animated_dialog: ^2.0.1
  otp_text_field: ^1.1.3
  flutter_polyline_points: ^1.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.2
  geolocator: ^9.0.1
  google_maps_flutter: ^2.2.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  path_provider: ^2.0.11
  photo_view: ^0.14.0
  place_picker: ^0.10.0
  flutter_chat_ui: ^1.6.4
  geocoding:
  flutter_rating_bar: ^4.0.1
  location: ^4.4.0
  permission_handler: ^10.0.2
  url_launcher: ^6.1.6
  pinput: ^2.1.4
  sliding_up_panel: ^2.0.0+1
  firebase_core_platform_interface: ^4.4.1

  provider: ^6.0.3
  razorpay_flutter: ^1.3.2
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  logger:
  # FireBase
  google_sign_in: ^6.0.2
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  firebase_core_web: ^2.2.2
  sms_autofill: ^2.2.0
  firebase_phone_auth_handler:
  pin_code_fields: ^7.4.0
  firebase_messaging: ^14.3.0
  fluttertoast:
  google_maps_flutter_web: ^0.4.0+7
  map_location_picker: ^1.1.0
  # GetX for Utils
  get: ^4.6.5
  get_storage: ^2.0.3

  # Connections

  socket_io_client: ^2.0.0



dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo/trucking-logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/logo/background.png"
  adaptive_icon_foreground: "assets/logo/trucking-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/json/
    - assets/translations/
    - assets/sounds/
    - assets/json/taxi/
    - assets/
    - assets/flags/

#    - android/
#    - android/app/
#    - android/app/src/
#    - android/app/src/main/
#    - android/app/src/main/res/
#    - android/app/src/main/res/mipmap-hdpi/
#    - android/app/src/main/res/mipmap-mdpi/
#    - android/app/src/main/res/mipmap-xhdpi/
#    - android/app/src/main/res/mipmap-xxhdpi/
#    - android/app/src/main/res/mipmap-xxxhdpi/
#    - android/app/src/main/java/
#    - android/app/src/main/java/io/
#    - android/app/src/main/java/io/flutter/
#    - android/app/src/main/java/io/flutter/plugins/
#    - android/app/src/main/kotlin/
#    - android/app/src/main/kotlin/com/
#    - android/app/src/main/kotlin/com/techhive/
#    - android/app/src/main/kotlin/com/techhive/sultancab/
#    - android/.idea/
#    - android/gradle/
#    - android/gradle/wrapper/
#    - android/.gradle/
#    - android/.gradle/vcs-1/
#    - android/.gradle/buildOutputCleanup/





