// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
    return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjNy_BqEUEcV_wZIU_eqr9Vm0ljMPNtKg',
    appId: '1:409671244772:android:b14aebc5f61d94d01d05f1',
    messagingSenderId: '409671244772',
    projectId: 'sultantaxi-b0dc2',
    storageBucket: 'sultantaxi-b0dc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB95fbW0Y89VXEZJ8fsuQM1MQqm4vPVkig',
    appId: '1:409671244772:ios:68a6d7511d3f9f5a1d05f1',
    messagingSenderId: '409671244772',
    projectId: 'sultantaxi-b0dc2',
    storageBucket: 'sultantaxi-b0dc2.appspot.com',
    androidClientId: '409671244772-02tcjo0vj5pd45fc6amf5vmna49k6e16.apps.googleusercontent.com',
    iosClientId: '409671244772-immacgmafi7brl8vqann2m183cl73hld.apps.googleusercontent.com',
    iosBundleId: 'com.techhive.sultancab',
  );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAL9XvC76KEJgRE_oECAgW1cPfOti3q_TU",
      authDomain: "tucking-app-c9418.firebaseapp.com",
      projectId: "tucking-app-c9418",
      storageBucket: "tucking-app-c9418.appspot.com",
      messagingSenderId: "236880847063",
      appId: "1:236880847063:web:77c7d95af4e2386bf15092",
      measurementId: "G-BELN9KVPQ5"
  );
}
